#!/usr/bin/env python2
"""
    drbdmanage - management of distributed DRBD9 resources
    Copyright (C) 2013 - 2016  LINBIT HA-Solutions GmbH
                               Author: R. Altnoeder

    For further information see the COPYING file.
"""

import drbdmanage_server

"""
Run the drbdmanage server
"""
if __name__ == "__main__":
    drbdmanage_server.main()
