#!/usr/bin/python

import drbdmanage_client

"""
Runs the drbdmanage client

The drbdmanage client is used to control
the local drbdmanage server
"""
if __name__ == "__main__":
    drbdmanage_client.main()

