#!/usr/bin/env python2
"""
    drbdmanage - management of distributed DRBD9 resources
    Copyright (C) 2013 - 2016  LINBIT HA-Solutions GmbH
                               Author: R. Altnoeder

    For further information see the COPYING file.
"""

import drbdctrl_init

"""
Runs the drbdctrl_init utility

drbdctrl_init is used for the initialization
of a new drbdmanage control volume
"""
if __name__ == "__main__":
    drbdctrl_init.main()

