#!/usr/bin/python

import drbdctrl_init

"""
Runs the drbdctrl_init utility

drbdctrl_init is used for the initialization
of a new drbdmanage control volume
"""
if __name__ == "__main__":
    drbdctrl_init.main()

